Repository NetsBlox/Snap--Build-Your-Own-Blocks, pull requests merged in 2018-07, with the labels that each got.

#656 script pic option downloads the image Fixes #655
  blocks.js
Labels: bug

#661 Hide deprecated blocks when searching. Closes #660
  objects-ext.js
  objects.js
Labels: enhancement, minor

#659 Close project messages after open. Fixes #658
  gui.js
  netsblox.js
Labels: bug, minor

#665 Remove "Save" option after adding Save A Copy. Fixes #664
  netsblox.js
Labels: bug, minor

#667 Reset action index on replay from beginning. Fixes #666
  objects.js
Labels: bug, minor

#673 Exit replay before opening new project. Fixes #672
  gui-ext.js
Labels: bug
