Repository NetsBlox/Snap--Build-Your-Own-Blocks, pull requests merged in 2018-08, with the labels that each got.

#676 Simulate mouse movement during dragAndDrop. Fixes #675
  test/snap-driver.js
Labels: bug, minor, testing

#678 multiple profiles for infinite/ongoing WebSocket monkey mode.
  test/ws-monkey.js
Labels: bug, enhancement

#686 Added label for loading RPC error watcher. Fixes #685
  store.js
Labels: bug

#688 Added fix for #346 back (it was overwritten by #678)
  actions.js
Labels: bug

#699 Added getEntireProject for opening copies of projects. Fixes #698
  cloud.js
  gui-ext.js
  netscloud.js
Labels: bug

#702 Download summary, stage, all script pics. Fixes #701
  blocks.js
  byob.js
  gui.js
  objects.js
Labels: bug, minor

#706 Remove rpc err watcher for Snap! serialization. Fixes #705
  netsblox.js
Labels: bug, minor

#708 Display "Opening proj" msg on open cloud proj. Fixes #707
  netsblox.js
Labels: bug

#710 Always use SnapActions.openProject. Fixes #709
  netsblox.js
Labels: bug

#718 Only revert block position on fail. Closes #717
  blocks.js
Labels: enhancement

#724 Don't optimize pos change if read only. Fixes #723
  actions-ext.js
  actions.js
  blocks.js
Labels: bug, minor

#729 Removed unnecessary clearing role. Fixes #728
  netsblox.js
Labels: bug
