Repository NetsBlox/Snap--Build-Your-Own-Blocks, pull requests merged in 2018-04, with the labels that each got.

#526 removed onLogin and onPassiveLogin
  netscloud.js
  room.js
Labels: netsblox

#530 removed unnecessary rename-role. Fixes #529
  store-ext.js
Labels: bug, minor

#532 Set project name if importing to single role app or from Snap!. Closes #531
  actions.js
  netsblox.js
  room.js
  store-ext.js
Labels: enhancement, minor

#528 Updated save to only save the current role. Closes #527
  gui-ext.js
  netsblox.js
  netscloud.js
  room.js
Labels: enhancement

#534 Do not accept actions if in action request. Fixes #533
  actions.js
Labels: bug

#536 Check if user action already exists before adding. Fixes #535
  actions.js
  undo.js
Labels: bug

#538 Suggest project export on failed cloud save. Closes #537
  netsblox.js
Labels: enhancement, minor

#540 Changed message to "Opening project". Closes #539
  netsblox.js
Labels: enhancement, minor

#545 Moved fn edits to original files. Closes #544
  blocks-ext.js
  blocks.js
  gui-ext.js
  gui.js
  netsblox.js
  objects-ext.js
  objects.js
  threads-ext.js
  threads.js
Labels: enhancement, extensibility, refactor

#547 Add unknown tabs after "Sounds". Fixes #546
  netsblox.js
Labels: bug, extensibility, minor

#549 Changed msg to 'Saved to the cloud'. Closes #548
  gui.js
Labels: enhancement, minor

#554 Ensure url is updated on open cloud project. Fixes #553
  netsblox.js
Labels: bug, minor

#556 Fixed connection refresh on message. Fixes #555
  websockets.js
Labels: bug
